version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gum
    main: .
    binary: gum
    env:
      - CGO_ENABLED=0
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.CommitSHA={{.Commit}}

archives:
  - id: gum
    name_template: "gum_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  prerelease: "false"

brews:
  - name: gum
    directory: Formula
    skip_upload: "false"
    repository:
      owner: ceffo
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/ceffo/gum"
    description: "Fork of charmbracelet/gum, a tool for glamorous shell scripts"
    license: MIT
    install: |
      bin.install "gum"
      generate_completions_from_executable(bin/"gum", "completion")
      (man1/"gum.1").write Utils.safe_popen_read(bin/"gum", "man")
    test: |
      assert_match "gum version", shell_output("#{bin}/gum --version")
